export default {
  SET_CHANNEL: 'SET_CHANNEL',
  CLEAR_CHANNEL: 'CLEAR_CHANNEL',
  SET_CHANNELS: 'SET_CHANNELS',
  MAKE_MESSAGE: 'MAKE_MESSAGE',
  SET_CHANNELS_WITH_CURRENT: 'SET_CHANNELS_WITH_CURRENT',
};
